//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public int PackageSize { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Enable { get; set; }
        public string Fingerprint { get; set; }
        public bool Verified { get; set; }
        public string File { get; set; }
    }
}
