//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeploy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageReceivingRecord
    {
        public int RecordId { get; set; }
        public string ReceiverHostName { get; set; }
        public int DeployId { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public bool HasDone { get; set; }
        public bool Successful { get; set; }
        public string Msg { get; set; }
        public string Error { get; set; }
    }
}
