//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeploy.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PackageReceivingRecordModel
    {
        [Display(Name = "接收主机")]
        public string ReceiverHostName { get; set; }
        [Display(Name = "开始时间")]
        public string StartTime { get; set; }
        [Display(Name = "结束时间")]
        public string EndTime { get; set; }
        [Display(Name = "是否完成")]
        public bool HasDone { get; set; }
        [Display(Name = "是否成功")]
        public bool Successful { get; set; }
        [Display(Name = "日志")]
        public string Msg { get; set; }
        [Display(Name = "错误")]
        public string Error { get; set; }
        public string Status { get; set; }
    }
}
